spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/newsdb
    username: postgres
    password: admin
    initialization-mode: always
    initialize: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
